PASSWORDS_DATABASE = "passwords.db"
KEY_ACCESS_DATABASE = "keys.db"

PASSWORD_KEY_TABLE_NAME = "password_key_table"
ACCESS_KEY_TABLE_NAME = "access_key_table"

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 40
